Update links that doesn't works
josephsalmon/HAX712X pull request #22
Opened 2024-12-13 13:09 UTC by EmilieAig

Update links that doesn’t works (when we click we obtain ‘not found’ or ‘404 error’), modifications on pages:
* Data Science
* Visualization
* Debugging & Profiling

2024-12-13 14:33 UTC, josephsalmon requested changes
Thanks for the feedabck. There are few files that need to be erase but otherwise LGTM.

2024-12-13 14:33 UTC, josephsalmon commented on .DS_Store
remove this file

2024-12-13 14:33 UTC, josephsalmon commented on Courses/.DS_Store
remove this file

2024-12-13 14:33 UTC, josephsalmon commented on Courses/Git/tp.quarto_ipynb
remove this file

2024-12-13 15:53 UTC, EmilieAig commented on .DS_Store
Thank you, it's done

2024-12-13 15:53 UTC, EmilieAig commented on Courses/.DS_Store
Thank you, it's done

2024-12-15 15:29 UTC, josephsalmon approved these changes
All good then.
I am validating the 1 pt bonus. Thanks again.

2024-12-15 15:29 UTC, merged